name: Deploy - AWS

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env

      - name: Run unit tests
        run: pnpm test -- --run

  deploy-aws:
    runs-on: ubuntu-22.04
    environment:
      name: 'production'
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env

      - name: Lint code
        run: pnpm lint

      - name: Build app
        run: pnpm run build

      - name: Deploy to AWS
        run: aws s3 sync ./dist s3://norbert-learning-app-s3-bucket
