name: Deploy - AWS

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env

      - name: Run unit tests
        run: pnpm test -- --run

  deploy-aws:
    runs-on: ubuntu-22.04
    environment:
      name: 'production'
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env

      - name: Lint code
        run: pnpm lint

      - name: Build app
        run: pnpm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Apply
        uses: ./.github/actions/terraform-apply
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS
        run: aws s3 sync ./dist s3://norbert-learning-app-s3-bucket
