name: Build and Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env

      - name: Run unit tests
        run: pnpm test -- --run

  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-netlify.outputs.deploy-url }}
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env

      - name: Lint code
        run: pnpm lint

      - name: Build app
        run: pnpm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
